### PR TITLE
Updated container to use Focal (n/t)

### PR DESCRIPTION
**Pull request by gbooker**

### CODE REVIEW

**Comment by gbooker** [comment]
@maxlabuche or @JayAndCatchFire (or anyone else): I don't have the ability to test these changes on ARM64 or ARMv7.  I'm wondering if you could give these changes a try and ensure that they still work there.

**Comment by JayAndCatchFire** [comment]
I can check this on ARM7 later today, but I don't have an ARM64 installation at the moment.

**Comment by gbooker** [comment]
OK, I'm going to go ahead and bump S6 in a separate commit since they are now on `2.1.0.0`.  It appears to work on AMD64.

**Comment by JayAndCatchFire** [comment]
I was unable to build the image.  I ran `docker build -t local/pms-docker:focal -f Dockerfile.armv7 https://github.com/plexinc/pms-docker.git#graham/focal` and got the following output.

```
Sending build context to Docker daemon  54.27kB
Step 1/17 : FROM ubuntu:20.04
 ---> 346078d30aa4
Step 2/17 : ARG S6_OVERLAY_VERSION=v2.1.0.0
 ---> Using cache
 ---> d83b3ed87dce
Step 3/17 : ARG S6_OVERLAY_ARCH=armhf
 ---> Using cache
 ---> ae1a892f25cc
Step 4/17 : ARG PLEX_BUILD=linux-armv7hf_neon
 ---> Using cache
 ---> 8363f21e3f9b
Step 5/17 : ARG PLEX_DISTRO=debian
 ---> Using cache
 ---> d7861ba92587
Step 6/17 : ARG DEBIAN_FRONTEND="noninteractive"
 ---> Using cache
 ---> f7a68c61f4c8
Step 7/17 : ENV TERM="xterm" LANG="C.UTF-8" LC_ALL="C.UTF-8"
 ---> Using cache
 ---> a23bea68ad10
Step 8/17 : ENTRYPOINT ["/init"]
 ---> Using cache
 ---> b1dc34a74f4c
Step 9/17 : RUN     apt-get update &&     apt-get install -y       tzdata       curl       xmlstarlet       uuid-runtime       unrar     &&         curl -J -L -o /tmp/s6-overlay-${S6_OVERLAY_ARCH}.tar.gz https://github.com/just-containers/s6-overlay/releases/download/${S6_OVERLAY_VERSION}/s6-overlay-${S6_OVERLAY_ARCH}.tar.gz &&     tar xzf /tmp/s6-overlay-${S6_OVERLAY_ARCH}.tar.gz -C / --exclude='./bin' &&     tar xzf /tmp/s6-overlay-${S6_OVERLAY_ARCH}.tar.gz -C /usr ./bin &&         useradd -U -d /config -s /bin/false plex &&     usermod -G users plex &&         mkdir -p       /config       /transcode       /data     &&         apt-get -y autoremove &&     apt-get -y clean &&     rm -rf /var/lib/apt/lists/* &&     rm -rf /tmp/* &&     rm -rf /var/tmp/*
 ---> Running in e06f2ad12df3
Get:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease [265 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease [111 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease [98.3 kB]
Err:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
  At least one invalid signature was encountered.
Get:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease [107 kB]
Err:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
  At least one invalid signature was encountered.
Err:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
  At least one invalid signature was encountered.
Err:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
  At least one invalid signature was encountered.
Reading package lists...
W: GPG error: http://ports.ubuntu.com/ubuntu-ports focal InRelease: At least one invalid signature was encountered.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports focal InRelease' is not signed.
W: GPG error: http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease' is not signed.
W: GPG error: http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease: At least one invalid signature was encountered.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease' is not signed.
W: GPG error: http://ports.ubuntu.com/ubuntu-ports focal-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports focal-security InRelease' is not signed.
The command '/bin/sh -c apt-get update &&     apt-get install -y       tzdata       curl       xmlstarlet       uuid-runtime       unrar     &&         curl -J -L -o /tmp/s6-overlay-${S6_OVERLAY_ARCH}.tar.gz https://github.com/just-containers/s6-overlay/releases/download/${S6_OVERLAY_VERSION}/s6-overlay-${S6_OVERLAY_ARCH}.tar.gz &&     tar xzf /tmp/s6-overlay-${S6_OVERLAY_ARCH}.tar.gz -C / --exclude='./bin' &&     tar xzf /tmp/s6-overlay-${S6_OVERLAY_ARCH}.tar.gz -C /usr ./bin &&         useradd -U -d /config -s /bin/false plex &&     usermod -G users plex &&         mkdir -p       /config       /transcode       /data     &&         apt-get -y autoremove &&     apt-get -y clean &&     rm -rf /var/lib/apt/lists/* &&     rm -rf /tmp/* &&     rm -rf /var/tmp/*' returned a non-zero code: 100
```

**Comment by JayAndCatchFire** [comment]
This is definitely an issue with the `ubuntu:20.04` `armv7` docker image and nothing wrong with your particular PR.  But I'd hesitate to merge this if the resulting image can't be built or tested. :disappointed:

**Review by NicoLiam — APPROVED** [review]

**Comment by gbooker** [comment]
So I looked into the error a bit and saw some people reporting that pruning the image for 20.04 solved this for them (by forcing it to re-pull the image) as well as others saying that they updated docker and it solved it.

I did find one reporting that it's a problem with one of the packages in the image making a system call that docker is blocking and that's why it is failing to check signatures.  Given that this one is now almost 3 months old and the 20.04 image is only 24 days old, I'd be really surprised if this is the case and it was still not fixed.

I guess, can you try to make sure that your docker is up to date and maybe see if you can force it to re-pull the 20.04 image just to make sure it is that.  I don't really want to merge this (at least not for ARM platforms) if images can no longer be made on ARM.

**Comment by JayAndCatchFire** [comment]
I gave this another shot.  Repulling the `ubuntu:20.04` image didn't change anything for me.  The instructions [here](https://askubuntu.com/a/1264921) helped.  I was able to get `apt-get update` to work using `docker run -it --rm --security-opt seccomp:unconfined ubuntu:20.04`.  The problem is, you can't (easily) build images with any `security-opt` settings [for portability reasons](https://github.com/moby/moby/issues/34454).  You can only run images with those settings.

FWIW, I'm running Rasbian as the host with:
```
docker-ce/buster,now 5:19.03.13~3-0~raspbian-buster armhf [installed]
libseccomp2/stable,now 2.3.3-4 armhf [installed]
```

So my Docker is up to date.  My libseccomp is a little behind what's recommended to solve the issue, but it's at the latest for buster.  There's a newer version on buster-backports, but that's not an official Raspbian repo.  That's a Debian repo.  I'm a little apprehensive to enable the whole repo as others have reported backports breaking their system.  And I could just install that one particular package, but that feels weird, too.  I'll have to think on it a little more.

In the meantime, this is an open issue for Docker which is _exactly_ the issue I'm dealing with: https://github.com/moby/moby/issues/40734

For the time being, I'm not sure what the correct course of action would be.  Options include:
- Not update my local plex docker image
- Wait for Raspbian Bullseye (which doesn't have a release date yet)
- Hope Raspbian gets an official backports repo/channel
- Add the Debian armhf buster-backports repo and hope for the best
- Install just the libseccomp2 package from buster-packports and hope there are no bugs or security holes that get discovered and patched that I'll miss by just installing a one-off package
- Wait and hope that Docker changes something that will fix it (see the linked issue above)

**Comment by gbooker** [comment]
I was afraid those would be the results.  Just hoping beyond hope that maybe it was something easily fixable.

So, I'm leaning toward doing one of:
1. Just update to Ubuntu 18.04 (supposedly this works)
1. Update to 20.04 for AMD64 and 18.04 for ARM platforms.

Could you test it with `ubuntu:18.04` as the base image just to make sure that it still works there?  What I read indicates that it does but I'd rather make sure.

**Comment by JayAndCatchFire** [comment]
I tried building and running using the `ubuntu:18.04` base image by changing only that line in `Dockerfile.armv7` on your branch.  It built just fine, but when I run it, I get this:

```
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

It then exits with error code 1.

**Comment by gbooker** [comment]
I wonder if that's the S6 version.  Maybe that S6 doesn't work with 18.04.

**Comment by cvandesande** [comment]
@JayAndCatchFire 
>   Add the Debian armhf buster-backports repo and hope for the best

I'm running Armbian, and thank you for your comment. I added the Debian buster backports and hoped for the best. It worked and I can now build docker images that use newer kernels..
```
$ apt-cache madison libseccomp2
libseccomp2 | 2.4.4-1~bpo10+1 | http://httpredir.debian.org/debian buster-backports/main armhf Packages
libseccomp2 | 2.4.4-1~bpo10+1 | http://deb.debian.org/debian buster-backports/main armhf Packages
libseccomp2 |    2.3.3-4 | http://httpredir.debian.org/debian buster/main armhf Packages

sudo apt-get -t buster-backports install libseccomp2
```
Didn't even need to reboot.

**Comment by danlsgiga** [comment]
I can confirm the Dockerfile.arm64 is working fine in my Raspberry Pi 4 using the `graham/focal` branch. Thank you! ;)

**Comment by nelsonb73** [comment]
Thank you! Worked for me as well.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by gbooker** [comment]
Thanks for the info; I have merged it now.

**Comment by JayAndCatchFire** [comment]
For anyone still grappling with the libseccomp issue on Raspberry Pi OS, I can recommend the instructions on [this blog entry](https://blog.samcater.com/fix-workaround-rpi4-docker-libseccomp2-docker-20/).  Big thank you to @xcellardoor if you happen to see this.

**Pull request merged**
