### PR TITLE
s6: v1.19.1.1

### PR DESCRIPTION
**Pull request by MindTooth**
Shipped version is far behind.

### CODE REVIEW

**Comment by gbooker** [comment]
What is the appreciable difference?  Aside from feature additions which we don't really need, I don't see any.

**Comment by MindTooth** [comment]
I had hoped that this might solve my problem with stalling containers.  Plex seems to stall my system on shutdown.

But I'll guess you are right.  Feel free to close.

**Comment by gbooker** [comment]
OK, since you can reproduce an issue and think this may solve it…

- Clone the repo
- Make your change
- Build and image
- Try the new image and see if it solves anything.

**Comment by MindTooth** [comment]
screen shot 2017-06-15 at 22 27 05

Well, that did nothing :-P

**Pull request closed without merging**
