### PR TITLE
Speed up health check

### PR DESCRIPTION
**Pull request by jsclayton**
I have this in my compose file as a fix for very slow startups of the container.

### CODE REVIEW

**Comment by jsclayton** [comment]
Found the docs where I based this change off long ago:

> The health check will first run interval seconds after the container is started, and then again interval seconds after each previous check completes.

So when `interval` is 200s Docker won't even try to consider it started for more than 3 minutes!

**Comment by larstobi** [comment]
@gbooker This change has been published on docker hub for the :latest tag but not for the :beta tag. Could we get this pushed for :beta as well?

**Comment by gbooker** [comment]
That's an issue being tracked by our build team and they will change the job to update the images.

**Comment by larstobi** [comment]
@gbooker They still haven't updated the job to include this health check speed-up. The beta docker image is still 9 months old.

Could we get an update top this, so that it does not take at least 3-4 minutes before the load balancer will send traffic to Plex? Restarts are slow without this fix.

**Pull request merged**
