### PR TITLE
doc: update helm chart README with instructions on how to add and use the chart repo

### PR DESCRIPTION
**Pull request by charlesthomas**

### CODE REVIEW

**Review by cilindrox — APPROVED** [review]
LGTM 👍 - thanks @charlesthomas

**Review by MarshallAsch — APPROVED** [review]

**Comment by cilindrox** [comment]
@charlesthomas do you mind bumping the chart version to a patch? (should be `0.1.8`) and we can cut a new version for this

**Comment by charlesthomas** [comment]
> @charlesthomas do you mind bumping the chart version to a patch? (should be `0.1.8`) and we can cut a new version for this

@cilindrox done!

**Comment by cilindrox** [comment]
thanks @charlesthomas !

**Pull request merged**
