### PR TITLE
Change connection timeout to overall timeout. 

### PR DESCRIPTION
**Pull request by midzelis**
In case connection succeeds, but no data returned.

### CODE REVIEW

**Comment by gbooker** [comment]
The `HEALTHCHECK` in the Dockerfile already has an overall timeout.  What situation is this supposed to cover that was not already done?

**Comment by midzelis** [comment]
It was leaving a lot of old curl processes around. This was happening due to trying to run /config on a NFS share, which isn't supported due to sqlite file locking issues. It would hang the webserver/plex server. The healthcheck could connect to the webserver, but there was no response, leaving the curl processes hanging around too. This will make the healthcheck more responsive.

**Comment by gbooker** [comment]
In the case you describe, did the healthcheck fail or did it pass when it should not have done so?

Also, 15 seconds is a bit short for an overall timeout.  There are some rare processes (such as database optimize) that can lock up the database for that long or longer on low end hardware (such as NAS devices).

**Comment by gbooker** [comment]
Closing due to lack of response.

**Comment by midzelis** [comment]
healthcheck didn't fail, didn't pass either. Just created new processes every X minutes. (didn't clean up processes either, strangely - maybe a docker healthcheck bug?)

I don't have a problem anymore, since I moved /config off of the bind mount (NFS) docker share, and using docker volume instead.

**Pull request closed without merging**
